### 
# @name login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "name": "Test",
    "password": "MonMotDePasseSecret123!"
}

### 
@authToken = {{login.response.body.token}}


### Créer une transaction (Dépense)
POST http://localhost:3000/api/transactions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "amount": 50.00,
    "type": "DEPENSE",
    "description": "Courses alimentaires",
}


### Créer une transaction (Gain)
POST http://localhost:3000/api/transactions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "amount": 1500.00,
    "type": "GAIN",
    "description": "Salaire mensuel"
}


### Récupérer toutes mes transactions
GET http://localhost:3000/api/transactions
Authorization: Bearer {{authToken}}

### Récupérer les transactions de Février 2026
GET http://localhost:3000/api/transactions?month=2&year=2026
Authorization: Bearer {{authToken}}


### Récupérer les STATISTIQUES de Février 2026
GET http://localhost:3000/api/transactions/stats?month=2&year=2026
Authorization: Bearer {{authToken}}